apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    pods: "100"
    requests.cpu: "16"
    requests.memory: "32Gi"
    limits.cpu: "24"
    limits.memory: "48Gi"
