global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets: [ "backend:8000" ]

  - job_name: "mysql"
    static_configs:
      - targets: [ "mysqld-exporter:9104" ]
