apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "products-db"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
          envFrom:
            - secretRef:
                name: db-secret
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
