apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
        - name: k6
          image: grafana/k6
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
          command: [ "sh", "-c", "sleep infinity" ]
      volumes:
        - name: k6-scripts
          emptyDir: { }
